In [1]:
import pandas as pd

df = pd.read_csv('prepped_phone_data.csv', index_col = 'customerID')
df

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,
7590-VHVEG,1,1,0,0,29.85,29.85,1
5575-GNVDE,34,0,1,1,56.95,1889.50,1
3668-QPYBK,2,0,0,1,53.85,108.15,0
7795-CFOCW,45,1,1,2,42.30,1840.75,1
9237-HQITU,2,0,0,0,70.70,151.65,0
...,...,...,...,...,...,...,...
6840-RESVB,24,0,1,1,84.80,1990.50,1
2234-XADUH,72,0,1,3,103.20,7362.90,1
4801-JZAZL,11,1,0,0,29.60,346.45,1
8361-LTMKD,4,0,0,1,74.40,306.60,0
3186-AJIEK,66,0,2,2,105.65,6844.50,1

In [2]:
from pycaret.classification import setup, compare_models, predict_model, save_model, load_model

In [3]:
automl = setup(df, target='Churn')

In [6]:
automl[6]

customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    0
7795-CFOCW    1
9237-HQITU    0
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    0
3186-AJIEK    1
Name: Churn, Length: 7032, dtype: int64

In [5]:
best_model = compare_models()

In [7]:
best_model

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=7424)

In [28]:
df.iloc[-2:-1].shape

(1, 7)

In [29]:
predict_model(best_model, df.iloc[-2:-1])

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Label,Score
customerID,,,,,,,,,
8361-LTMKD,4,0,0,1,74.4,306.6,0,0,0.5008

In [30]:
save_model(best_model, 'LDA')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='Churn',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strate...
                 ('dummy', Dummify(target='Churn')),
                 ('fix_perfect', Remove_100(target='Churn')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
                                     learning_rate=1.0, n_estimators=50,
                                     random_state=7424)]],
          verbose=False),
 'LDA.pkl')

In [31]:
import pickle

with open('LDA_model.pk', 'wb') as f:
    pickle.dump(best_model, f)

In [32]:
with open('LDA_model.pk', 'rb') as f:
    loaded_model = pickle.load(f)

In [38]:
loaded_lda = load_model('LDA')

Transformation Pipeline and Model Successfully Loaded

In [39]:
predict_model(loaded_lda, new_data)

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Label,Score
customerID,,,,,,,,
8361-LTMKD,4,0,0,1,74.4,306.6,0,0.5008

In [9]:
from IPython.display import Code

In [19]:
Code('Downloads/new_churn_data.py')

customerID,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,charge_per_tenure
9305-CKSKC,22,1,0,2,97.4,811.7,36.89545455
1452-KNGVK,8,0,1,1,77.3,1701.95,212.74375
6723-OKKJM,28,1,0,0,28.25,250.9,8.960714286
7832-POPKP,62,1,0,2,101.7,3106.56,50.10580645
6348-TACGU,10,0,0,1,51.15,3440.97,344.097

In [20]:
%run Downloads/new_churn_data.py

NameError: name 'customerID' is not defined

This assignment was quite challenging for me, and I still didnt even really complete it. I had a tough time with multiple aspects of the work and wish I could've had more